# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_locale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=15, unique=True)),
                ('sort', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_translate', to='menu.Category')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_translate_locale', to='app_locale.AppLocaleName', to_field='locale_code')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='menu.Category')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='ItemChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_choice', to='menu.Item')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_choice_option', to='menu.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_translate', to='menu.Item')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_translate_locale', to='app_locale.AppLocaleName', to_field='locale_code')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='menu.Item')),
            ],
            options={
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='VariationTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_translate_locale', to='app_locale.AppLocaleName', to_field='locale_code')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_translate', to='menu.Variation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variationtranslate',
            unique_together=set([('variation', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set([('item', 'sort')]),
        ),
        migrations.AlterUniqueTogether(
            name='itemtranslate',
            unique_together=set([('item', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='itemchoice',
            unique_together=set([('item', 'option', 'choice')]),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('category', 'sort')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslate',
            unique_together=set([('category', 'locale')]),
        ),
    ]
