# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('category', 'sort')},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('item', 'sort')},
        ),
    ]
