# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_locale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConstant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('constant_value', models.CharField(max_length=500)),
                ('staff_only', models.BooleanField()),
                ('superuser_only', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AppConstantTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_value', models.CharField(max_length=500)),
                ('app_constant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_constant_translate', to='app_constant.AppConstant')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_constant_translate_locale', to='app_locale.AppLocaleName', to_field='locale_code')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appconstanttranslate',
            unique_together=set([('app_constant', 'locale')]),
        ),
    ]
