# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_locale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('constant_value', models.CharField(max_length=500)),
                ('staff_only', models.BooleanField()),
                ('superuser_only', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ConstantGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_group_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('constant_group_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ConstantGroupTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_group_name', models.CharField(max_length=500)),
                ('constant_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constant_group_translate', to='app_constant.ConstantGroup')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constant_group_translate_locale', to='app_locale.LocaleName', to_field='locale_code')),
            ],
        ),
        migrations.CreateModel(
            name='ConstantTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant_value', models.CharField(max_length=500)),
                ('constant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constant_translate', to='app_constant.Constant')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constant_translate_locale', to='app_locale.LocaleName', to_field='locale_code')),
            ],
        ),
        migrations.AddField(
            model_name='constant',
            name='constant_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constant', to='app_constant.ConstantGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='constanttranslate',
            unique_together=set([('constant', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='constantgrouptranslate',
            unique_together=set([('constant_group', 'locale')]),
        ),
    ]
