"""
Django settings for generic_store project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ['DJANGO_DEBUG']) == 1

ALLOWED_HOSTS = [
  '127.0.0.1',
]

# Application definition
INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'django_celery_results',
  'rest_framework',
  'account',
  'app_locale',
  'app_constant',
  'app_mailer',  
  'contact_us',
  'menu',
  'store_info',
  'user_interface',
]

MIDDLEWARE = [
  'django.middleware.common.BrokenLinkEmailsMiddleware',
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'generic_store.urls'

TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': ["static"],
    'APP_DIRS': True,
    'OPTIONS': 
    {
      'context_processors': 
      [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
      ],
    },
  },
]

WSGI_APPLICATION = 'generic_store.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
  'default': {
    'ENGINE': os.environ['DJANGO_DATABASE_ENGINE'],
    'NAME': os.environ['DJANGO_DATABASE_NAME'],
    'USER': os.environ['DJANGO_DATABASE_USER'],
    'PASSWORD': os.environ['DJANGO_DATABASE_PASSWORD'],
    'HOST': os.environ['DJANGO_DATABASE_HOST'],
    'PORT': os.environ['DJANGO_DATABASE_PORT'],
  }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'account.User'

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# rest framework
REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': 
  (
    'rest_framework.authentication.BasicAuthentication',
    'rest_framework.authentication.SessionAuthentication',
  ),
  'TEST_REQUEST_RENDERER_CLASSES': 
  (
    'rest_framework.renderers.JSONRenderer',
  )
}

#email settings
EMAIL_USE_TLS = True
EMAIL_HOST = os.environ['DJANGO_EMAIL_HOST']
EMAIL_HOST_USER = os.environ['DJANGO_EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['DJANGO_EMAIL_HOST_PASSWORD']
EMAIL_PORT = int(os.environ['DJANGO_EMAIL_PORT'])
DEFAULT_FROM_EMAIL = os.environ['DJANGO_DEFAULT_FROM_EMAIL']

#Celery configs
BROKER_URL = os.environ['DJANGO_CELERY_BROKER_URL']
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_IMPORTS = ('app_mailer.tasks', )

#key constants for sessions
SESSION_KEY = {}
SESSION_KEY['CURRENT_LOCALE'] = 'CURRENT_LOCALE'

#error email handling
ADMINS = [
  ('Chang Zheng', 'chang.s.zheng@gmail.com'),
]
MANAGERS = [
  ('Chang Zheng', 'chang.s.zheng@gmail.com'),
]