# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLocaleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale_code', models.CharField(max_length=15, unique=True)),
                ('locale_name', models.CharField(max_length=50)),
            ],
        ),
    ]
